#! /usr/bin/ruby
require 'pathname'

# change to "osx" if you want an OSX playground
# change to "tvos" if you want a tvOS playground
platform = "ios"

contents_xcplayground = <<XML
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<playground version='5.0' target-platform='#{platform}'>
    <timeline fileName='timeline.xctimeline'/>
</playground>
XML

time = Time.now.strftime "%Y%m%d-%H%M%S"
path = Pathname.new "/tmp/playgrounder/#{time}.playground"
path.rmtree if path.exist?
path.mkpath
File.open(path+"contents.xcplayground", 'w') {|f| f.write(contents_xcplayground) }

section_1_swift = "import #{platform == "osx" ? "Cocoa" : "UIKit"}\n\n"
File.open(path+"Contents.swift", 'w') {|f| f.write(section_1_swift) }

`open #{path}`
