#! /usr/bin/ruby
require 'pathname'

platform = "iphonesimulator" # or "macosx"
contents_xcplayground = <<XML
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<playground version='1.0' sdk='#{platform}'>
    <sections>
        <code source-file-name='section-1.swift'/>
    </sections>
</playground>
XML

time = Time.now.strftime "%Y%m%d-%H%M%S"
path = Pathname.new "/tmp/playgrounder/#{time}.playground"
path.rmtree if path.exist?
path.mkpath
File.open(path+"contents.xcplayground", 'w') {|f| f.write(contents_xcplayground) }
`open #{path}`